import crypto from 'node:crypto';

/**
 * Razorpay helpers for the E2E suite.
 *
 * Two distinct things live here:
 *
 *  1. **Real signature math.** The signatures the app verifies are genuine
 *     HMACs over real inputs — the tests compute them exactly the way
 *     Razorpay does, using the same secret the app reads. A test that faked
 *     signature verification would prove nothing, since signature forgery is
 *     one of the exploits being regression-tested.
 *
 *  2. **A fake gateway client.** Razorpay's SDK is constructed at module load
 *     in services/paymentService.js, services/refundService.js and
 *     util/payoutHelper.js, so it must be mocked before those modules import.
 *     The fake is programmable per-test: it can report a payment as
 *     uncaptured, return a mismatched amount, throw a timeout, or count how
 *     many times the gateway was actually called — which is precisely the
 *     assertion the concurrency tests need ("exactly one transfer").
 */

export const TEST_KEY_SECRET = 'e2e_test_key_secret';
export const TEST_WEBHOOK_SECRET = 'e2e_test_webhook_secret';

/** The signature Razorpay Checkout returns to the client after a payment. */
export const paymentSignature = (orderId, paymentId, secret = TEST_KEY_SECRET) =>
  crypto.createHmac('sha256', secret).update(`${orderId}|${paymentId}`).digest('hex');

/**
 * Builds a signed webhook request body + headers.
 * Returns the EXACT bytes to send — the app HMACs `req.rawBody`, so the body
 * must be transmitted verbatim rather than re-serialised, or verification
 * fails for the wrong reason.
 */
export const signedWebhook = ({ event, payload, eventId, createdAt = 1700000000, secret = TEST_WEBHOOK_SECRET }) => {
  const body = JSON.stringify({ event, payload, created_at: createdAt });
  const signature = crypto.createHmac('sha256', secret).update(body).digest('hex');
  return {
    body,
    headers: {
      'Content-Type': 'application/json',
      'x-razorpay-signature': signature,
      ...(eventId ? { 'x-razorpay-event-id': eventId } : {}),
    },
  };
};

export const capturedPaymentWebhook = ({ paymentId, orderId, amountPaise, bookingId, eventId }) =>
  signedWebhook({
    event: 'payment.captured',
    eventId,
    payload: {
      payment: {
        entity: {
          id: paymentId,
          order_id: orderId,
          amount: amountPaise,
          status: 'captured',
          notes: bookingId ? { bookingId: String(bookingId) } : {},
        },
      },
    },
  });

/**
 * Programmable fake Razorpay client.
 *
 * `calls` records every gateway invocation so tests can assert on the number
 * of real gateway hits, not just on the resulting DB state — the difference
 * matters for double-payout and over-refund, where the DB can look correct
 * while the gateway was called twice.
 */
export class RazorpayFake {
  constructor() {
    this.reset();
  }

  reset() {
    this.calls = { ordersCreate: [], paymentsFetch: [], paymentsRefund: [], payoutsCreate: [] };
    this.state = {
      // paymentId -> entity returned by payments.fetch
      payments: new Map(),
      // orderId -> entity
      orders: new Map(),
    };
    this.failures = {};
    this.seq = 0;
  }

  /** Make the next (or every) call to a given method throw. */
  failOn(method, error = new Error('gateway unavailable'), times = Infinity) {
    this.failures[method] = { error, remaining: times };
  }

  #maybeFail(method) {
    const failure = this.failures[method];
    if (failure && failure.remaining > 0) {
      failure.remaining -= 1;
      throw failure.error;
    }
  }

  /** Register a payment as the gateway would report it. */
  seedCapturedPayment({ paymentId, orderId, amountPaise, status = 'captured' }) {
    this.state.payments.set(paymentId, { id: paymentId, order_id: orderId, amount: amountPaise, status });
    return paymentId;
  }

  /**
   * Register an order with a specific receipt. The reconciliation job finds
   * orphaned payments by searching orders on `receipt: rcpt_bk_<bookingId>`,
   * so a test for it has to be able to plant an order under a chosen receipt
   * rather than one generated by orders.create.
   */
  seedOrder({ orderId, receipt, amountPaise, notes = {} }) {
    this.state.orders.set(orderId, {
      id: orderId, receipt, amount: amountPaise, currency: 'INR', notes, status: 'paid',
    });
    return orderId;
  }

  get orders() {
    return {
      create: async (params, headers) => {
        this.#maybeFail('orders.create');
        this.calls.ordersCreate.push({ params, headers });
        const id = `order_E2E${++this.seq}`;
        const entity = { id, amount: params.amount, currency: params.currency, receipt: params.receipt, notes: params.notes, status: 'created' };
        this.state.orders.set(id, entity);
        return entity;
      },
      fetch: async (orderId) => {
        this.#maybeFail('orders.fetch');
        return this.state.orders.get(orderId) || { id: orderId, amount: 0, currency: 'INR' };
      },
      all: async ({ receipt }) => {
        this.#maybeFail('orders.all');
        const items = [...this.state.orders.values()].filter((o) => o.receipt === receipt);
        return { items, count: items.length };
      },
      fetchPayments: async (orderId) => {
        this.#maybeFail('orders.fetchPayments');
        const items = [...this.state.payments.values()].filter((p) => p.order_id === orderId);
        return { items, count: items.length };
      },
    };
  }

  get payments() {
    return {
      fetch: async (paymentId) => {
        this.#maybeFail('payments.fetch');
        this.calls.paymentsFetch.push(paymentId);
        const entity = this.state.payments.get(paymentId);
        if (!entity) throw new Error(`payment ${paymentId} not found`);
        return entity;
      },
      refund: async (paymentId, params) => {
        this.#maybeFail('payments.refund');
        this.calls.paymentsRefund.push({ paymentId, params });
        return { id: `rfnd_E2E${++this.seq}`, payment_id: paymentId, amount: params.amount, status: 'processed' };
      },
    };
  }

  get payouts() {
    return {
      create: async (params, headers) => {
        this.#maybeFail('payouts.create');
        this.calls.payoutsCreate.push({ params, headers });
        return { id: `pout_E2E${++this.seq}`, status: 'processed', ...params };
      },
    };
  }

  get contacts() {
    return { create: async (params) => ({ id: `cont_E2E${++this.seq}`, ...params }) };
  }

  get fund_accounts() {
    return {
      create: async (params) => ({ id: `fa_E2E${++this.seq}`, ...params }),
      update: async (id, params) => ({ id, ...params }),
    };
  }
}

export const razorpayFake = new RazorpayFake();
export default razorpayFake;
